version: '2.18'

services: 
  web:
    build: .
    ports: 
      - 80:80
    volumes:
      - .:/var/www/html
  

  database:
    build: 
      context: ./database
    ports:
      - 3306:3306
    #Habililta autenticación con contraseña desde mysql
    command: --default-authentication-plugin=mysql_native_password 

    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=examen
      - MYSQL_USER=emilio
      - MYSQL_PASSWORD=root 
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default     

  phpmyadmin:
    build: 
      context: ./database
    ports:
      - 8000:80
    environment:
      - MYSQL_USER=emilio
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

    depends_on: 
      - database 